from . import personal
from . import position
from . import department
from . import formation
from . import secure
from . import interviews
from . import vacancies
from . import licences
from . import vacation
from . import suspensions
from . import admonishments